#!/bin/sh
#PBS -N preprocess_s2-b4
#PBS -o preprocess_s2-b4.log
#PBS -e preprocess_s2-b4.err
#PBS -q low
#PBS -l nodes=1:ppn=24
#PBS -l mem=10G

module load flexbar

cd /home/shiqinghua/gjn1106/pipeline/scrna
echo "step2 Trim reads on R1, processing batch-4"

time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L2/L2_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L2/L2_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L2/L2_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L2/L2_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L2/L2_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L3/L3_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L3/L3_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L3/L3_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L3/L3_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L3/L3_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L5/L5_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L5/L5_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L5/L5_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L5/L5_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L5/L5_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M1/M1_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M1/M1_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M1/M1_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M1/M1_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M1/M1_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M2/M2_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M2/M2_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M2/M2_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M2/M2_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M2/M2_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M4/M4_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M4/M4_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M4/M4_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M4/M4_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M4/M4_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0a/N0a_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0a/N0a_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0a/N0a_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0a/N0a_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0a/N0a_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0b/N0b_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0b/N0b_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0b/N0b_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0b/N0b_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0b/N0b_R1.clean.extracted_trimTSO.fastq


