#!/bin/sh
#PBS -N preprocess_s2-b2
#PBS -o preprocess_s2-b2.log
#PBS -e preprocess_s2-b2.err
#PBS -q low
#PBS -l nodes=1:ppn=24
#PBS -l mem=10G

module load flexbar

cd /home/shiqinghua/gjn1106/pipeline/scrna
echo "step2 Trim reads on R1, processing batch-2"

time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G9F/G9F_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G9F/G9F_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G9F/G9F_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G9F/G9F_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G9F/G9F_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G9M/G9M_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G9M/G9M_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G9M/G9M_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G9M/G9M_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G9M/G9M_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H4/H4_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H4/H4_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H4/H4_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H4/H4_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H4/H4_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H5/H5_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H5/H5_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H5/H5_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H5/H5_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H5/H5_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H6/H6_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H6/H6_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H6/H6_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H6/H6_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H6/H6_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I4/I4_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I4/I4_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I4/I4_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I4/I4_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I4/I4_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I5/I5_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I5/I5_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I5/I5_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I5/I5_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I5/I5_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I6/I6_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I6/I6_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I6/I6_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I6/I6_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I6/I6_R1.clean.extracted_trimTSO.fastq


