#!/bin/sh
#PBS -N preprocess_s5-b1
#PBS -o preprocess_s5-b1.log
#PBS -e preprocess_s5-b1.err
#PBS -q middle
#PBS -l nodes=1:ppn=24
#PBS -l mem=10G

module load samtools
module load Anaconda3

cd /home/shiqinghua/gjn1106/pipeline/scrna
echo "step5 Reads assignment, processing batch-1"

echo "processing E8M"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/E8M
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o E8M.gene_assigned -R BAM E8M.Aligned.sortedByCoord.out.dedup.bam
rm E8M.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing E8M2"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/E8M2
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o E8M2.gene_assigned -R BAM E8M2.Aligned.sortedByCoord.out.dedup.bam
rm E8M2.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing F7F"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/F7F
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o F7F.gene_assigned -R BAM F7F.Aligned.sortedByCoord.out.dedup.bam
rm F7F.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing F7M"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/F7M
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o F7M.gene_assigned -R BAM F7M.Aligned.sortedByCoord.out.dedup.bam
rm F7M.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing G10F"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G10F
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o G10F.gene_assigned -R BAM G10F.Aligned.sortedByCoord.out.dedup.bam
rm G10F.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing G10M"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G10M
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o G10M.gene_assigned -R BAM G10M.Aligned.sortedByCoord.out.dedup.bam
rm G10M.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing G8F"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G8F
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o G8F.gene_assigned -R BAM G8F.Aligned.sortedByCoord.out.dedup.bam
rm G8F.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing G8M"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G8M
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o G8M.gene_assigned -R BAM G8M.Aligned.sortedByCoord.out.dedup.bam
rm G8M.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing G9F"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G9F
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o G9F.gene_assigned -R BAM G9F.Aligned.sortedByCoord.out.dedup.bam
rm G9F.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing G9M"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G9M
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o G9M.gene_assigned -R BAM G9M.Aligned.sortedByCoord.out.dedup.bam
rm G9M.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing H4"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H4
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o H4.gene_assigned -R BAM H4.Aligned.sortedByCoord.out.dedup.bam
rm H4.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing H5"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H5
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o H5.gene_assigned -R BAM H5.Aligned.sortedByCoord.out.dedup.bam
rm H5.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing H6"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/H6
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o H6.gene_assigned -R BAM H6.Aligned.sortedByCoord.out.dedup.bam
rm H6.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing I4"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I4
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o I4.gene_assigned -R BAM I4.Aligned.sortedByCoord.out.dedup.bam
rm I4.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing I5"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I5
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o I5.gene_assigned -R BAM I5.Aligned.sortedByCoord.out.dedup.bam
rm I5.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


echo "processing I6"
cd /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/I6
time featureCounts -a /home/shiqinghua/gjn1106/reference/mm10/Annotation/gencode.vM21.withERCC92.gtf --extraAttributes gene_id,gene_name,gene_type -T 24 -o I6.gene_assigned -R BAM I6.Aligned.sortedByCoord.out.dedup.bam
rm I6.Aligned.sortedByCoord.out.dedup.bam.featureCounts.bam


