#!/bin/sh
#PBS -N preprocess_s1
#PBS -o preprocess_s1.log
#PBS -e preprocess_s1.err
#PBS -q low
#PBS -l nodes=1:ppn=20
#PBS -l mem=10G

module load Anaconda3

home=~/pipeline/scrna
project=MouseGonocyte2019
barcode_file="$home/reference/barcodes.txt"
cd "$home/scripts"

echo "step1 Extract barcodes and UMIs and add to read names"
time python 01-extract_barcode_UMI.py $home $project $barcode_file 20