#!/bin/sh
#PBS -N preprocess_s2-b5
#PBS -o preprocess_s2-b5.log
#PBS -e preprocess_s2-b5.err
#PBS -q low
#PBS -l nodes=1:ppn=24
#PBS -l mem=10G

module load flexbar

cd /home/shiqinghua/gjn1106/pipeline/scrna
echo "step2 Trim reads on R1, processing batch-5"

time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N1/N1_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N1/N1_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N1/N1_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N1/N1_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N1/N1_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N3/N3_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N3/N3_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N3/N3_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N3/N3_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N3/N3_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N6/N6_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N6/N6_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N6/N6_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N6/N6_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N6/N6_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/O7F/O7F_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/O7F/O7F_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/O7F/O7F_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/O7F/O7F_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/O7F/O7F_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/O7M/O7M_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/O7M/O7M_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/O7M/O7M_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/O7M/O7M_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/O7M/O7M_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/P0/P0_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/P0/P0_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/P0/P0_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/P0/P0_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/P0/P0_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/Q9F/Q9F_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/Q9F/Q9F_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/Q9F/Q9F_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/Q9F/Q9F_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/Q9F/Q9F_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/Q9M/Q9M_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/Q9M/Q9M_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/Q9M/Q9M_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/Q9M/Q9M_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/Q9M/Q9M_R1.clean.extracted_trimTSO.fastq


