#!/bin/sh
#PBS -N preprocess_s2-b1
#PBS -o preprocess_s2-b1.log
#PBS -e preprocess_s2-b1.err
#PBS -q low
#PBS -l nodes=1:ppn=24
#PBS -l mem=10G

module load flexbar

cd /home/shiqinghua/gjn1106/pipeline/scrna
echo "step2 Trim reads on R1, processing batch-1"

time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/E8M/E8M_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/E8M/E8M_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/E8M/E8M_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/E8M/E8M_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/E8M/E8M_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/E8M2/E8M2_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/E8M2/E8M2_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/E8M2/E8M2_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/E8M2/E8M2_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/E8M2/E8M2_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/F7F/F7F_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/F7F/F7F_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/F7F/F7F_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/F7F/F7F_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/F7F/F7F_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/F7M/F7M_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/F7M/F7M_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/F7M/F7M_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/F7M/F7M_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/F7M/F7M_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G10F/G10F_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G10F/G10F_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G10F/G10F_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G10F/G10F_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G10F/G10F_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G10M/G10M_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G10M/G10M_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G10M/G10M_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G10M/G10M_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G10M/G10M_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G8F/G8F_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G8F/G8F_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G8F/G8F_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G8F/G8F_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G8F/G8F_R1.clean.extracted_trimTSO.fastq


time flexbar --adapter-min-overlap 7 --adapter-trim-end LEFT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/TSO.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G8M/G8M_R1.clean.extracted.fq.gz --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G8M/G8M_R1.clean.extracted_trimTSO
time flexbar --adapter-min-overlap 7 --adapter-trim-end RIGHT --adapters /home/shiqinghua/gjn1106/pipeline/scrna/reference/adapters_polyAnT.fa --min-read-length 16 --threads 24 --reads /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G8M/G8M_R1.clean.extracted_trimTSO.fastq --target /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G8M/G8M_R1.clean.extracted_trimTSO_trimPolyA -z GZ
rm /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/G8M/G8M_R1.clean.extracted_trimTSO.fastq


