#!/bin/sh
#PBS -N preprocess_s3-b4
#PBS -o preprocess_s3-b4.log
#PBS -e preprocess_s3-b4.err
#PBS -q middle
#PBS -l nodes=1:ppn=24
#PBS -l mem=10G

module load STAR

cd /home/shiqinghua/gjn1106/pipeline/scrna
echo "step3 STAR alignment, processing batch-4"

STAR --runThreadN 24 --genomeDir /home/shiqinghua/gjn1106/reference/mm10/STARIndexERCC/gencode.vM21 --readFilesIn /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L2/L2_R1.clean.extracted_trimTSO_trimPolyA.fastq.gz --readFilesCommand zcat --outFilterMultimapNmax 50 --winAnchorMultimapNmax 50 --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L2/L2 

STAR --runThreadN 24 --genomeDir /home/shiqinghua/gjn1106/reference/mm10/STARIndexERCC/gencode.vM21 --readFilesIn /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L3/L3_R1.clean.extracted_trimTSO_trimPolyA.fastq.gz --readFilesCommand zcat --outFilterMultimapNmax 50 --winAnchorMultimapNmax 50 --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L3/L3 

STAR --runThreadN 24 --genomeDir /home/shiqinghua/gjn1106/reference/mm10/STARIndexERCC/gencode.vM21 --readFilesIn /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L5/L5_R1.clean.extracted_trimTSO_trimPolyA.fastq.gz --readFilesCommand zcat --outFilterMultimapNmax 50 --winAnchorMultimapNmax 50 --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/L5/L5 

STAR --runThreadN 24 --genomeDir /home/shiqinghua/gjn1106/reference/mm10/STARIndexERCC/gencode.vM21 --readFilesIn /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M1/M1_R1.clean.extracted_trimTSO_trimPolyA.fastq.gz --readFilesCommand zcat --outFilterMultimapNmax 50 --winAnchorMultimapNmax 50 --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M1/M1 

STAR --runThreadN 24 --genomeDir /home/shiqinghua/gjn1106/reference/mm10/STARIndexERCC/gencode.vM21 --readFilesIn /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M2/M2_R1.clean.extracted_trimTSO_trimPolyA.fastq.gz --readFilesCommand zcat --outFilterMultimapNmax 50 --winAnchorMultimapNmax 50 --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M2/M2 

STAR --runThreadN 24 --genomeDir /home/shiqinghua/gjn1106/reference/mm10/STARIndexERCC/gencode.vM21 --readFilesIn /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M4/M4_R1.clean.extracted_trimTSO_trimPolyA.fastq.gz --readFilesCommand zcat --outFilterMultimapNmax 50 --winAnchorMultimapNmax 50 --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/M4/M4 

STAR --runThreadN 24 --genomeDir /home/shiqinghua/gjn1106/reference/mm10/STARIndexERCC/gencode.vM21 --readFilesIn /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0a/N0a_R1.clean.extracted_trimTSO_trimPolyA.fastq.gz --readFilesCommand zcat --outFilterMultimapNmax 50 --winAnchorMultimapNmax 50 --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0a/N0a 

STAR --runThreadN 24 --genomeDir /home/shiqinghua/gjn1106/reference/mm10/STARIndexERCC/gencode.vM21 --readFilesIn /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0b/N0b_R1.clean.extracted_trimTSO_trimPolyA.fastq.gz --readFilesCommand zcat --outFilterMultimapNmax 50 --winAnchorMultimapNmax 50 --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /home/shiqinghua/gjn1106/pipeline/scrna/data/MouseGonocyte2019/N0b/N0b 

